# Generated by Django 3.1.7 on 2021-02-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210225_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinginfo',
            old_name='paid',
            new_name='paid_driver',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='patient_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DriverPayment',
        ),
    ]
