# Generated by Django 3.1.7 on 2021-02-26 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210225_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_time', models.TimeField(default=datetime.time(12, 0))),
                ('notification', models.BooleanField(default=False)),
                ('medicine', models.ManyToManyField(related_name='assigned_medicine', to='main.Medicine')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_medicine', to='main.student')),
            ],
        ),
    ]
