# Generated by Django 3.1.7 on 2021-03-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencymsg',
            name='solve',
            field=models.BooleanField(default=False),
        ),
    ]
