# Generated by Django 3.1.7 on 2021-03-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_emergencymsg_solve'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
