# Generated by Django 3.1.7 on 2021-04-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='on_duty',
            field=models.BooleanField(default=False),
        ),
    ]
