# Generated by Django 3.1.7 on 2021-04-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_driver_on_duty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalroute',
            old_name='driver_spotted',
            new_name='deliverd',
        ),
    ]
