# Generated by Django 3.1.7 on 2021-04-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_hospitalroute_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='released',
            new_name='on_road',
        ),
    ]
