# Generated by Django 3.1.7 on 2021-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210415_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='on_road',
            field=models.BooleanField(default=False),
        ),
    ]
